### ISSUE TITLE
Don't use HTTP URLs to download releases

### ISSUE THREAD

**Issue by zoffixznet** [Tyil/lonestar#1]
Spotted some [HTTP URLs](https://github.com/Tyil/lonestar/blob/master/lib/lonestar/latest_available#L5).

We have HTTPS hosted binaries here: https://rakudo.perl6.org/downloads/

In a couple of weeks, [new rakudo.org](https://github.com/perl6/perl6.org/issues/96) will launch and it'll by fully HTTPS and offer specific routes for latest releases like, http://perl6.org:4242/latest/star/win64 for latest win64 star. And the site has an idea of what releases are available, so we can hack up some sort of API for release info fetching, if needed.

**Comment by Tyil** [comment]
With the advent of the new https://rakudo.org website, I've updated LoneStar to use the new URLs, which are all using HTTPS now.
